repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Filesystem Secret Scan
        entry: trufflehog filesystem .
        language: system
        pass_filenames: false
        stages: [commit]
