repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Secret Scan
        entry: trufflehog git file://. --max-depth 1 --only-verified --fail
        language: system
        pass_filenames: false
        stages: [commit]
